### ISSUE TITLE
Does not cohabitate with other filters well

### ISSUE THREAD

**Issue by greg-hellings** [rpkilby/tox-factor#12]
Having both tox-factor and tox-travis living together, for instance, causes one to override the other. Since they both read the full list of environments directly from the config, whichever one gets executed last will override the settings of the other.

**Comment by rpkilby** [comment]
For reference, conversation at https://github.com/tox-dev/tox-travis/issues/143

**Comment by rpkilby** [comment]
Hi. I'm going to close this for now as "not intended usage". That said, happy to reevaluate depending on the conversation over on tox-travis.
