### ISSUE TITLE
Migrate to tox-dev and v4 support

### ISSUE THREAD

**Issue by gaborbernat** [rpkilby/tox-factor#17]
Hello, would you consider moving the project under the tox-dev umbrella? See documentation under https://tox.readthedocs.io/en/rewrite/plugins.html#adoption-of-a-plugin-under-tox-dev-github-organization 

Furthermore, tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by icemac** [comment]
I'd also like to see this plug-in supporting tox v4.

**Comment by gaborbernat** [comment]
No need, this feature is now part of core.

**Comment by icemac** [comment]
That's nice to hear.

**Comment by robsdedude** [comment]
> No need, this feature is now part of core.

@gaborbernat that's great news. Can you leave some extra info (e.g., a link, or the name of the flag) for future reference?

**Edit:** I found `-f`/`--factor` in the [docs](https://tox.wiki/en/latest/cli_interface.html#tox-run--f), but couldn't find the PR that introduces it. Either way, thanks for the great work!

**Comment by rpkilby** [comment]
Thanks @gaborbernat for implementing this in core!
